### ISSUE TITLE
Tasks are forgot after restart

### ISSUE THREAD

**Issue by erazemk** [dahenson/agenda#100]
I have added Agenda to startup.

After every reboot, even if I add tasks, they are deleted after logging in again.

Edit: Seems to happen even if not added to startup (I have reinstalled the program).

Edit2: I've tried closing the program by pressing its X button and the notes were saved, so it probably has something to do with saving the notes, which should be done after pressing the enter button.
I'm guessing that the notes aren't properly saved when restarting, as the app is ?forcefully? shut down...

**Comment by dahenson** [comment]
It's true that the tasks are really only saved on a "safe" exit, either when you press the `x` or when you press `esc` on your keyboard. I will look into fixing this issue in a future release.

**Comment by hormozy** [comment]
Also getting this issue.

**Comment by Brin-o** [comment]
Hi, I'm getting this issue as well. I'll to close it with X now but I feel like it should save on Alt + F4/restart as well
