### ISSUE TITLE
Seemingly unlimited characters when editing a task

### ISSUE THREAD

**Issue by dahenson** [dahenson/agenda#19]
The task entry has a character limit, but editing tasks does not have the same limit, so you can write giant paragraphs after you add the task.

**Comment by be1** [comment]
So, is it worth keeping the limit in the task entry ?

**Comment by be1** [comment]
I think https://github.com/dahenson/agenda/commit/cdc11434b4ba0bf7e99e73be2525a940d0ab6258 fixes it.
