### ISSUE TITLE
Selection color on the entry is white and unreadable 

### ISSUE THREAD

**Issue by Philip-Scott** [dahenson/agenda#3]
It looks a bit odd ;)

![screenshot from 2017-05-24 11 28 05](https://cloud.githubusercontent.com/assets/10786508/26414219/18f6a350-4074-11e7-80b9-40f6e392b0ee.png)

**Comment by dahenson** [comment]
Good catch! I forgot to remove some stupid styling. Should be fixed now with the latest commit.
