### ISSUE TITLE
Nothing Appeared

### ISSUE THREAD

**Issue by hrstwn** [dahenson/agenda#33]
[INFO 13:25:17.873810] Application.vala:153: Agenda version: 1.0.6
[INFO 13:25:17.873896] Application.vala:155: Kernel version: 4.4.0-78-generic
[WARNING 13:25:17.912596] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 13:25:17.912684] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 13:25:17.912780] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[ERROR 13:25:17.955124] [GLib-GIO] Settings schema 'net.launchpad.agenda-tasks' is not installed
Trace/breakpoint trap (core dumped)

**Comment by dahenson** [comment]
Thanks. This issue should be fixed with the latest release. Please update and try again.
