### ISSUE TITLE
Task text is not visible in dark theme.

### ISSUE THREAD

**Issue by nagurumalab** [dahenson/agenda#34]
![screenshot](https://cloud.githubusercontent.com/assets/1259559/26538500/b44f6bfe-4464-11e7-904f-928797d0b45e.png)

Text color is black, making it very difficult to see the tasks in dark them.

**Comment by franky436** [comment]
+1

**Comment by jojobyte** [comment]
Same problem here.

**Comment by dahenson** [comment]
I don't see this as a bug, because I didn't design Agenda to work with a dark theme. Can you tell me how/why you are using a dark theme on it?

**Comment by franky436** [comment]
We are using dark mode globally, for all apps. I'd assume this is being used by many users simply for the fact it's beautiful. It can easily be turned on in elementary tweaks. http://ow.ly/QGcI30cbMuC

**Comment by nagurumalab** [comment]
Yes as @franky303 said, I used elementary tweaks to enable the dark theme for all apps.

**Comment by dahenson** [comment]
Okay, I will work on fixing this issue soon. Seems that there are a lot more people interested in running dark theme than I thought.
