### ISSUE TITLE
Add support for todo.txt

### ISSUE THREAD

**Issue by krille-chan** [dahenson/agenda#37]
todo.txt is a universal and simple language for saving tasks and supportet by many other apps. It is such simple as write every task into one line in a txt-file.
If Agenda would support todo.txt, we would be able to sync our tasks easy with a cloud, nextcloud or syncthing. We simply need a function to open a todo.txt file and to create a new one. The saving of changes could be automatically.

**Comment by dahenson** [comment]
I have considered adding todo.txt support in the past, but I am not convinced that it will add as much value to Agenda as it would to another task app. Agenda is meant to be minimal, lightweight, and self-contained. I will consider adding basic support for todo.txt if it will stay out of the way of the main interface, but it may not come for a few releases.

**Comment by BharatKalluri** [comment]
Really looking forward for this, would be a game changer for me :-)

**Comment by dahenson** [comment]
Now that some time has passed, I am going to have to close this as "won't fix." At this point, I feel like adding todo.txt functionality is outside of the scope of this project.

There is another app called "Yishu" (https://github.com/lainsce/yishu) in the elementary OS command center that is a phenomenal todo.txt interface. If you haven't tried it out, I highly recommend it.
