### ISSUE TITLE
Co-maintenance of Flathub repo

### ISSUE THREAD

**Issue by Alexander-Wilms** [dahenson/agenda#41]
I created a Flatpak manifest, so that Agenda can be installed on any distro (https://github.com/flathub/flathub/pull/37).
Would you like to co-maintain that build recipe, i.e. have write-access to the GitHub repo?

**Comment by dahenson** [comment]
I don't know enough about Flatpaks to make a call on this yet. I'm really glad you've done the legwork to get it working! Thank you! I had heard that there was a possibility of creating an elementary OS runtime for Flatpaks at which point, I would be more likely to help maintain a Flatpak that uses that particular runtime to avoid theme breakage, etc.

**Comment by TingPing** [comment]
> I had heard that there was a possibility of creating an elementary OS runtime for Flatpaks at which point, I would be more likely to help maintain a Flatpak that uses that particular runtime to avoid theme breakage, etc.

There is no point in an Elementary runtime existing. Themes will be tied to the Gtk version and since Gtk3 is stabilized and never changing you just make sure the work on 3.20+. (Very sadly Ubuntu LTS uses 3.18)

**Comment by Alexander-Wilms** [comment]
There's now an elementary BaseApp, on top of which Agenda ist now built: https://github.com/flathub/flathub/pull/437

**Comment by dahenson** [comment]
I am going to go ahead and close this issue. It seems that there are people successfully using Agenda as downloaded from flathub. I appreciate your work in getting flatpak working for Agenda, and I look forward to learning from your work for [future AppCenter Flatpak versions](https://medium.com/elementaryos/elementary-appcenter-flatpak-b1f970a33861).
