### ISSUE TITLE
Make delete key working as is in entry editing

### ISSUE THREAD

**Issue by nick87720z** [dahenson/agenda#45]
When entry is edited, would be better to unbound Delete key, making it available as editing key.
For now when it is pressed during editing, agenda just crashes.

**Comment by nick87720z** [comment]
Same note about escape key. When i press it to exit entry editing, entire application exists.
There are even more issues with keys, probably need to play with code in fork :)

**Comment by dahenson** [comment]
I had known about the `Esc` key, but did not know about pressing `Del`. Can confirm that these are both issues. I'll look into fixing them soon.
