### ISSUE TITLE
Transparent window background

### ISSUE THREAD

**Issue by nick87720z** [dahenson/agenda#46]
In addition to previous hints for rounded and compact windows - would be nice let its background have some transparency, with a floating key in dconf.

**Comment by nick87720z** [comment]
Hm, i missed fix for issue #7 - don't know, is it enough, never played with custom css gtk theming

**Comment by dahenson** [comment]
I'm not sure about allowing a transparent background. I specifically styled the app to be white, and I feel like transparency is a bit necessary for the app. Having good contrast for readable tasks is important to me.

**Comment by TobiOkanlawon** [comment]
THANK YOU DAHENSON, cause I just downloaded the app and it's transparent. There's no option to change it back, or at least I can't see one (because it's transparent). At least there should be a way to accommodate both options. Nope, there's no option to change the background color.

**Comment by be1** [comment]
Hello. I don't understand if it is the expected behaviour, but, in Elementary 7, the window is completely transparent by default. This makes it unreadable. I am using the dark theme in Pantheon preferences.

**Comment by be1** [comment]
I made a quick fix to **not** set the window transparent, in https://github.com/dahenson/agenda/commit/f6198fef322dea1bcc2f5b15385ef8e570cce91d but I have to find out why the @bg_color is set to transparent in Elementary 7.1.
