### ISSUE TITLE
Delete task without marking it as complete

### ISSUE THREAD

**Issue by lokesh-krishna** [dahenson/agenda#50]
Currently it is only possible to delete a task by marking it complete. Could it please be made possible to delete a task without having to mark it complete first?

**Comment by dahenson** [comment]
I'll have to think through how that would look, but it's a good point. Would a context menu (right-click) with "Delete Task" in it be enough?

**Comment by lokesh-krishna** [comment]
> Would a context menu (right-click) with "Delete Task" in it be enough?

I guess that would do. Is there anything in the elementary OS HIG about how to handle things like this (surfacing additional options on demand)?

**Comment by dahenson** [comment]
I'll have to read through the HIG again, but I don't think there's anything about how to handle this kind of thing. If anything, I'm sure the elementary team frowns on hiding functionality behind context menus.

I'm actually considering making the 'x' invisible on all tasks unless the cursor is hovering over the task. That way, you can delete any task, but it doesn't clutter up the interface.

**Comment by lokesh-krishna** [comment]
> I'm actually considering making the 'x' invisible on all tasks unless the cursor is hovering over the task. That way, you can delete any task, but it doesn't clutter up the interface.  

That sounds really good!

**Comment by yeboahnanaosei** [comment]
> I'm actually considering making the 'x' invisible on all tasks unless the cursor is hovering over the task. That way, you can delete any task, but it doesn't clutter up the interface.

Sounds really really good

**Comment by dahenson** [comment]
I finally got around to implementing this functionality in my latest commit #65. The release should hit AppCenter soon, I just need to polish a few things up.
