### ISSUE TITLE
quick way to close all completed tasks

### ISSUE THREAD

**Issue by sgpthomas** [dahenson/agenda#51]
After I have finished many tasks, it is annoying to go through and remove all of them. I think having some way to close all complete tasks would improve this app.

**Comment by dahenson** [comment]
I'll have to look at adding a button for this function. I would expect it to only show up when tasks are marked "complete". Thank you for the suggestion.

**Comment by gxhamster** [comment]
I think I will work on this

**Comment by gxhamster** [comment]
There was a function to remove the tasks already just added a button to connect them

**Comment by be1** [comment]
Yep, https://github.com/dahenson/agenda/commit/b9331148e1ef92062849343fcf0774de444be404 fixes that issue.
