### ISSUE TITLE
clarify license: GPLv3 or LGPLv3?

### ISSUE THREAD

**Issue by decathorpe** [dahenson/agenda#63]
The license headers in *.vala files suggest the project is licensed under the LGPLv3 license, however the newly included LICENSE file contains the GPLv3 license (with some characters missing at the start, I guess that was a Copy-Paste-Error).

**Comment by dahenson** [comment]
With the latest commit, I believe I cleared up the discrepancy. Everything should reflect that this project is GPLv3. Please let me know if I missed anything. I will be pushing a new release to AppCenter soon.

**Comment by decathorpe** [comment]
Looks good from my point of view. :+1: Thanks!
