### ISSUE TITLE
Logo design for Agenda

### ISSUE THREAD

**Issue by linadesteem** [dahenson/agenda#66]
Hi, my name is Munzir, I am a logo designer. I see that your project has no logo yet. So I am thinking to contribute to this project by making a logo. My main aims are to support open source project like yours, designing a logo to help projects build its identity. So what do you think? here are some concept that you might like:

![image](https://user-images.githubusercontent.com/35618068/40133440-febee9ec-5969-11e8-9ac7-005b0d9cd58e.png)
![image](https://user-images.githubusercontent.com/35618068/40133448-049bab0c-596a-11e8-9dbc-459f5d915f18.png)

Tell me if you like it in another color, or if you want me to make another concept :)

Regards
Munzir Burrahman
Logo Designer

**Comment by dahenson** [comment]
Thanks for the contribution! It looks like you do good work, and those are some interesting concepts. However, I am not looking for a new logo at this time. This application has a logo generously designed by the inimitable @harveycabaguio 

If you feel like you have some tweaks or suggestions for the existing icon set, feel free to submit some issues or pull requests and Harvey and I would be glad to review them. Thanks!
