### ISSUE TITLE
Add some minimal CSS to make the titlebar white

### ISSUE THREAD

**Issue by danirabbit** [dahenson/agenda#7]
```
.titlebar {
    background-image: none;
    border: none;
}
```

looks like this:

![screenshot from 2017-05-24 17 02 10](https://cloud.githubusercontent.com/assets/7277719/26430557/fb3743fe-40a2-11e7-8cb6-2fa416ee6312.png)

**Comment by dahenson** [comment]
I didn't know this was possible! Imma do it!
