### ISSUE TITLE
Undo/Redo for Tasks

### ISSUE THREAD

**Issue by imasaru** [dahenson/agenda#76]
I accidentally deleted a really long task once, and tried Ctrl + Z to no avail... It would be nice if we could undo/redo operations in Agenda.

Thank you.

**Comment by dahenson** [comment]
Thank you for this suggestion. I'm sorry you lost your task! I will see what I can do to keep a temporary history so that users can recover their previous tasks.

**Comment by dahenson** [comment]
This feature has been added in #99, which will be coming out in the next release! Thanks again for the feature request.
