### ISSUE TITLE
Completed tasks go down the list.

### ISSUE THREAD

**Issue by aRmanNM** [dahenson/agenda#81]
i really like the minimal approach with this application. i even use it with my none pantheon DEs. but i think it would be better if completed tasks could go down the list. it helps concentrating more on active ones.

**Comment by be1** [comment]
https://github.com/dahenson/agenda/commit/fe6b72db7551122aed6a219da886d4bca84eb4c7 fixes that:  press Ctrl+S to sort the completed tasks to the bottom.
