### ISSUE TITLE
Clicking an area not containing a task should deselect a task

### ISSUE THREAD

**Issue by phase1geo** [dahenson/agenda#84]
If I have a task selected and I click on an area in the task list which does not contain a task, it would be nice if the selected task was deselected.

**Comment by dahenson** [comment]
I have been meaning to file and fix this bug for a long time. Thanks for bringing it to my attention again. I will work to put a fix in the next release.

**Comment by be1** [comment]
This is now fixed for a long time. Closing the issue.
