### ISSUE TITLE
Remember last known position

### ISSUE THREAD

**Issue by dracid** [dahenson/agenda#86]
I've included Agenda in Startup, but every time it launches in the middle of the screen. (common to other widget apps, too)
Can it be made so that it remembers its last known position? 

That would be loads better! Thanks!

**Comment by dahenson** [comment]
Thanks for your bug report! I have not tested what Agenda does if it's included on Startup, but it is supposed to remember its last position on the screen. I have tested this, and it works on all of my different installations. Can you give me more details about your use case? Are you using elementary OS 5.0, or a previous version?

**Comment by dracid** [comment]
I've been using Juno since Beta2 and this is the same install, but with all the latest updates and latest Agenda from the app store.
When I come home, I'll test it separately (outside of just startup). Thanks for a quick reply!

**Comment by dracid** [comment]
So I've checked this out with Agenda 1.0.12 and latest Loki updates (same install as Beta2, but latest updates).
- If  I quit Agenda and re-launch it by hand - it remembers the old position, perfectly!
- However, if it is launched on startup, it just starts in the middle of the screen. 

Any thoughts?

**Comment by erazemk** [comment]
@dracid After installing and adding the app to startup, it seems to work perfectly and positions itself where it should. Have you tested this bug again recently?
