### ISSUE TITLE
Automatically sort finished tasks to the top

### ISSUE THREAD

**Issue by JonnyCodewalker** [dahenson/agenda#90]
Maybe only upon restart, but this way the app becomes less cluttered and you know that you can simply look at the bottom to find the tasks to be done.

**Comment by be1** [comment]
Hello,
Now https://github.com/dahenson/agenda/commit/fe6b72db7551122aed6a219da886d4bca84eb4c7 gives a way to sort completed tasks to the **bottom** of the list. I think tasks to be done should remain on top, not the contrary. But, later I will provide a way to fine-tune the sorting style in the app settings, then you will be able to sort completed tasks on top of the list.

**Comment by be1** [comment]
commit 4a4348a7848f14f79aad867a7be2289c85539c14 allows now to sort finished tasks upward. It depends on a boolean setting that, for now, has no other way to be changed than using `dconf-editor` . Hopefully, soon will appear a setting popup in Agenda, I think.
