### ISSUE TITLE
Add appdata to be translated

### ISSUE THREAD

**Issue by NathanBnm** [dahenson/agenda#91]
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by dahenson** [comment]
Thank you so much for the feedback! I am working on changing the build system, and I will be adding the ability to translate the appdata file. Once that's done, I'll have to get volunteers to submit translations. I would love to make the app as accessible as possible, and this will be one more step towards that goal.

**Comment by NathanBnm** [comment]
Great! Yes I assume you have to pass on meson build. So don't forget to notify me when it will be ready, I can translate into French :+1:.

**Comment by ryonakano** [comment]
Should be fixed in #106
