### ISSUE TITLE
entire window is transparent

### ISSUE THREAD

**Issue by syphoxy** [dahenson/agenda#92]
I'm trying to use Agenda but for some reason it comes out completely transparent.

I am currently using Gnome on Wayland on Fedora 29. I am also using the dark theme in Gnome.

I've attached a screenshot.

![screenshot from 2019-02-01 20-34-54](https://user-images.githubusercontent.com/234569/52157901-ec9def00-2660-11e9-8503-982edd7b75ca.png)

any idea?

**Comment by syphoxy** [comment]
~I just realized that I cannot take screenshots in Wayland. let me see if I can produce a screenshot somehow.~

ok, I fixed the screenshot.

**Comment by dahenson** [comment]
I haven't had a chance to test this at all (mainly because I am primarily concerned with elementary). Can you give me a few more details? Did you install this via flatpak, or did you build it yourself, or did you install it some other way? Thanks.

**Comment by juarezfranco** [comment]
It happened to me, I use numix theme, with the default theme is ok

**Comment by TobiOkanlawon** [comment]
The same thing happened to me, and I'm on fedora too

**Comment by ryonakano** [comment]
![Screenshot from 2019-11-16 19-31-17](https://user-images.githubusercontent.com/26003928/68991934-b1934200-08a7-11ea-9311-02fb6afe3313.png)

I guess this is a stylesheet issue−the app window gets transparent other than in elementary stylesheet. Maybe some defined values used in [the app stylesheet](https://github.com/dahenson/agenda/blob/master/data/Agenda.css) like `@bg_color` or `@selected_bg_color` are not set in other stylesheets for other themes?
