### ISSUE TITLE
fails to build with vala 0.43.6+, 0.42.5+, and 0.40.13+

### ISSUE THREAD

**Issue by decathorpe** [dahenson/agenda#93]
Building agenda on fedora 30/rawhide fails now, after the update from vala 0.43.4 to vala 0.43.6. This is the only error message in the build log:

```
cc: error: /builddir/build/BUILD/agenda-1.0.12/build/src/Agenda.c: No such file or directory
cc: fatal error: no input files
```

The full build log can be seen at https://kojipkgs.fedoraproject.org//work/tasks/4118/32364118/build.log

**Comment by decathorpe** [comment]
The same error now also occurs after updating vala from 0.40.12 to 0.40.13.

**Comment by decathorpe** [comment]
Also happening since the 0.42 branch was updated from 0.42.4 to 0.42.5.

**Comment by dahenson** [comment]
Thank you for these helpful reports. I'm sorry I haven't gotten back to you on this. I am currently only targeting elementary Juno, so this isn't a show-stopper, but I would like to get a development environment going with newer builds of Vala so that I can test and fix these issues.

**Comment by decathorpe** [comment]
No need to apologize, we're all busy.

Since it's possible that this is a CMake issue (I remember seeing an error like this before), maybe it's already not a problem anymore in your development branch since you're using meson now.

**Comment by decathorpe** [comment]
Just FYI, it looks like this was a bug in vala after all - because after the update from vala 0.44.3 to 0.44.4 (the latest stable release), agenda builds fine again.

**Comment by dahenson** [comment]
Thanks for following up on this! I appreciate your diligence.
